project:
  type: website
  output-dir: docs

website:
  title: "Enrique Quezada-Llanes"
  google-analytics: "G-Q9BGGFZRB1"
  navbar:
    pinned: true
    background: white 
    foreground: gray-700
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - cv.qmd
      - about.qmd
      - icon: github
        href: https://github.com/equezadallanes/
      - icon: twitter
        href: https://twitter.com/oequezada
  search: false
  page-footer: "College of the Holy Cross <br> 1 College Street <br> Worcester, MA 01610 <br> equezada (at) holycross.edu<br><br>" 
    
resources:
  - CNAME
  

format:
  html:
    theme: 
      - flatly
      - html/custom.scss
    css: styles.css
    linestretch: 1.8

editor: visual

filters:
  - newpagelink.lua
  