---
title: "About"
---

<!--
I am a PhD candidate in the Department of Political Science at Rice University and a graduate fellow for the Religion and Public Life Program at the Boniuk Institute for Religious Tolerance.
-->

Before starting my PhD, I earned a bachelor of music degree in clarinet performance from Union College (Lincoln, Nebraska) in 2016. During my time there, I founded and conducted the Recreare Ensemble, a chamber orchestra whose highlights included a performance of Beethoven's First Symphony and a staging of Mozart's musical comedy *Impresario* I also conducted the college's choral, orchestral, and symphonic band ensembles in several performances. In the year between college and attending graduate school, I conducted a string orchestra of homeschoolers and taught clarinet and beginning piano in the Lincoln area.

I was previously a graduate fellow for the Religion and Public Life Program at the Boniuk Institute for Religious Tolerance and for the Center for the United States and Mexico at the Baker Institute for Public Policy. In the latter position, I hosted and produced the [*Judy Ley Allen Mexico Centered*](https://podcasts.apple.com/us/podcast/judy-ley-allen-mexico-centered/id1316117842){target="_blank"} podcast, where I interviewed many academics as well as current and former government officials from the United States and Mexico.

Outside of academic work, I enjoy reading, listening to podcasts, brewing coffee, and playing clarinet whenever I can (which is not often these days).

