---
title: "Research"
---

## Journal Articles


Mrchkovska, Nela, and **Enrique Quezada-Llanes**. 2025. ["Voices from the Pulpit: Discourse on Racial Justice and Gun Violence from American Clergy."](https://doi.org/10.1080/00380237.2025.2516814) *Sociological Focus* 58 (3): 323–343. 
<button class="btn btn-primary  btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample">Abstract</button>

```{=html}
<div class="collapse" id="collapseExample2">
  <div class="card card-body">
    Over the past years, many religious congregations have addressed issues of racial justice and gun violence following the killing of George Floyd and recent mass shootings in places like Uvalde, Texas, Atlanta, Georgia, and Monterey Park, California. However, existing work suggests that which places of worship respond and how they respond depends on congregational, denominational, and contextual factors. Most of this work relies on self-reports from congregants or clergy. We take a different approach by directly observing the messages religious individuals hear during worship. Using large language models (LLMs) to help identify which sermons include discussions of racial justice or gun violence, we analyze close to 200,000 sermons across 2,863 US congregations. We found that, even though discussions of racial issues and gun violence are relatively rare events in religious sermons, major tragic events like the killing of George Floyd and several mass shootings taking place between 2018 and 2023 increase the probability of congregation leaders addressing these topics. We also found that, in some cases, mainline Protestant sermons are more responsive to these tragic events compared to evangelical Protestant sermons.
  </div>
  <br>
</div>
```


Zárate, Marques G., **Enrique Quezada-Llanes**, and Angel D. Armenta. 2024. ["Se Habla Español: Spanish-language Appeals and Candidate Evaluations in the United States."](https://doi.org/10.1017/S0003055423000084) *American Political Science Review* 118 (1): 363–79. 
<button class="btn btn-primary  btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Abstract</button> [<button class="btn btn-primary  btn-sm" type="button">PDF</button>](files/APSR_2024.pdf){target="_blank"}


```{=html}
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    Political candidates use Spanish-language appeals in efforts to increase their support among Hispanic voters. We argue that candidates, Hispanic or not, can use Spanish to signal closeness to Hispanics and posit that the effectiveness of these appeals is conditional on proficiency. To test this, we run two experiments where participants listen to an audio clip of a hypothetical candidate’s stump speech. We vary the ethnicity of the candidate (Anglo or Hispanic) and the language of the speech (English, non-native Spanish, and native-like Spanish). We find that Hispanic support for the Anglo and Hispanic candidates is higher in the native-like Spanish condition compared with the English-only condition. Relative to the English condition, non-native Spanish does not increase support for the Anglo candidate, but it decreases support for the Hispanic candidate. We find mixed effects for Anglo participants. Our results suggest that candidates can effectively appeal to Hispanic voters using Spanish-language messages.
  </div>
  <br>
</div>
```




## Other Writing

**Quezada-Llanes, Enrique.** 2025. ["Ethnic, Linguistic, and Religious Minority Participation and Representation in the United States."](https://www.oxfordbibliographies.com/display/document/obo-9780199756223/obo-9780199756223-0383.xml) In *Oxford Bibliographies in Political Science,* ed. Mark P. Jones. New York: Oxford University Press. [<button class="btn btn-primary  btn-sm" type="button">PDF</button>](files/OB_2025.pdf){target="_blank"}


Olson, Shayla and **Enrique Quezada-Llanes**. 2024. "How Sermons Became More Political in the Trump Era." In *Trump, White Evangelical Christians, and American Politics: Change and Continuity,* eds. Paul A. Djupe and A.E. Sokhey. University of Pennsylvania Press.

**Quezada-Llanes, Enrique.** 2020. “U.S. Citizenship Test.” In *Voting and Political Representation in America: Issues and Trends,* ed. Mark P. Jones.


## Under Review

"'Here Am I, Send Me': Religious Cues, Group Membership, and Candidate Evaluations"


## Work in Progress

"The Contours of Latine Political Interests" (with Marques G. Zárate)

"Drawing Religious Group Boundaries in a Polarized Partisan Context" (with Shayla F. Olson)

"From Streets to Sermons: Effects of Proximity and Exposure to Protests and Gun Violence on Politicization of US Congregations" (with Nela Mrchkovska)

"When Candidates Become Preachers: Religious Appeals in Campaign Advertisements in the U.S. from 2010-2020" (with Pedro Magarao Ribeiro*)

"The Role of Spanish Language on Latino Group Consciousness"




