---
title: "Teaching"
---

## College of the Holy Cross

POLS 299-F06 - Religion in American Politics: Fall 2025


## Agnes Scott College

POL 102 - Introduction to American Politics: Spring 2024, Spring 2025

POL 226 - Approaches to Political Science (methods): Fall 2023, Fall 2024

POL/PSY 309 - Political Psychology: Fall 2024

POL/REL 310 - Religion and Politics in the United States: Fall 2023, Fall 2024

POL 330 - Latine Politics in the U.S.: Spring 2024 [<button class="btn btn-primary  btn-sm" type="button">Syllabus</button>](files/POL330_Spring24.pdf){target="_blank"}, Spring 2025

## Rice University

### Instructor of Record

POLI 328 - Latino Politics in the U.S., Spring 2023

FWIS 184 - Understanding Religion in American Politics, Fall 2022

POLI 238 - Religion and Politics in the United States, Fall 2021


### Teaching Assistant

POLI 210 - Introduction to American Politics (Dr. Lyn Ragsdale, instructor), Fall 2020

POLI 212 - Introduction to Comparative Politics (Dr. Leslie Schwindt-Bayer, instructor), Spring 2019
