---
title: "Modeling God"
date: 05-03-2018
categories: [Religion]
draft: false
---

If there is one thing I hold dear from what I've learned in my first year in graduate school, it's the language of models, whether these are theoretical or statistical models. I have not only found them useful to think about social science-y questions (which is, of course, the reason I learned them), but also for how I think about God. A model is not only a good representation of how we think something works, but thinking about models also gives an understanding of how we think about anything. As a "spiritual and religious" person, I naturally apply this framework to my understanding of God and how we can relate to Him.

The main lesson I draw from thinking in terms of models, is that it gives language to what I think is happening all around me. From the person crossing the street in a hurry (maybe they are late for an appointment?) to why we use our phones so much (is it the overstimulation of saturated color?). A model is a summary of a set of causal statements that help us make sense of something.

It's what helps us navigate the world.

We need it.

But here's the key thing: they are incomplete representations of the true phenomena they seek to explain.

We reduce an event or object to a set of characteristics we can work with. If we, for example, were to build a model of a skyscraper, would we include a sewage system and to-scale functional elevator systems? Well, it depends on what we are trying to model. You would include a sewage system if you were tasked with figuring out how that would work on that hypothetical (or real) building. You would definitely not waste your time with elevators since they are irrelevant for the task at hand.

So it goes with any model. What are we trying to get at? That's what we'll include in the model. And this is exactly what we do when we think about God. We build models to explain the experiences we have that transcend the material world, or which include an aspect that is just beyond what we can describe. We find language, we find statements, we find analogies, things that can help us grasp our experiences with God.

We all have models of God. These may be models we inherited from our parents or grandparents that get updated with our own experiences. Some people decide the models they were passed down simply don't work and proceed to discard them. For others, they might just need an overhaul.

The other key point this suggests is that models tell you as much about the thing you are trying to explain/understand as they tell you about who build this model. They point to what we care about, the experiences that begged the questions addressed, the contexts, and, mainly, the assumptions (often unquestioned) that we won't compromise on (our first principles or axioms).

So, our understanding of God talks about God, but it also talks about us. It talks about our context, our wishes and hopes.

Having multiple, evolving models of God does not necessarily mean the thing we are trying to explain is not there or that God changes on a whim. The fact that multiple models exists and change says more about the ways in which we make sense of the world. Our understanding is finite and evolving, and so are our models.

At best, our models of God are true representations of just one aspect of His infinite character and nature.

What this means is not that we should stop talking about God, quite the opposite. We should engage in conversation of what this 'thing' we experience is, and we should do so with the most humble of attitudes.

Lastly, we should engage in these conversations with a deep awareness of what it is we talk about when we talk about God.

